### PR TITLE
Return errors instead of printing to logs

### LINKED ISSUE #880: [BUG] 1.5.1 uses log.Printf
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Commit 666c197fc9157896b57515c3a3326c3f8c8319fe is a huge commit with no useful log message, and I keep finding new issues with it.

One of the issues is that it included a bunch of error handling using `log.Printf`.  gorilla/websocket is a generally useful library, and it should not be making any assumptions about my application's logging infrastructure; using `log.Printf` for logging is a clear violation of this basic principle.

Please revert commit 666c197fc9157896b57515c3a3326c3f8c8319fe.

### Expected Behavior

A low-lever library should not be doing logging on behalf of the application.

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by apoorvajagtap**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Go Version Update
- [ ] Dependency Update

## Description
With #840 debug messages were printed to stderr, as this wasn't very application friendly. With this, the noise in the logs will be reduced, without impacting error handling.

## Related Tickets & Documents

- Closes #880 

## Added/updated tests?

- [ ] Yes
- [x] No, and this is why: current tests does not cover the scenario of stderr logs, so no impact on tests with the changes.
- [ ] I need help with writing tests

## Run verifications and test

- [x] `make verify` is passing
- [x] `make test` is passing

### CODE REVIEW

File: proxy.go [hunk 1]
```diff
@@ -58,29 +57,20 @@ func (hpd *httpProxyDialer) Dial(network string, addr string) (net.Conn, error)
...
 	// Read response. It's OK to use and discard buffered reader here becaue
 	// the remote server does not speak until spoken to.
 	br := bufio.NewReader(conn)
 	resp, err := http.ReadResponse(br, connectReq)
 	if err != nil {
-		if err := conn.Close(); err != nil {
-			log.Printf("httpProxyDialer: failed to close connection: %v", err)
-		}
-		return nil, err
+		return nil, errors.Join(conn.Close(), err)
```
Comment (GreenMarmot) [inline proxy.go:68]: Reorder so that primary error is first.

    return nil, errors.Join(err, conn.Close())

File: proxy.go [hunk 2]
```diff
@@ -58,29 +57,20 @@ func (hpd *httpProxyDialer) Dial(network string, addr string) (net.Conn, error)
...
 	}
 
 	if resp.StatusCode != http.StatusOK {
-		if err := conn.Close(); err != nil {
-			log.Printf("httpProxyDialer: failed to close connection: %v", err)
-		}
 		f := strings.SplitN(resp.Status, " ", 2)
-		return nil, errors.New(f[1])
+		return nil, errors.Join(conn.Close(), err, errors.New(f[1]))
```
Comment (GreenMarmot) [inline proxy.go:73]: `err` does not belong here.   Primary error first.

    return nil, errors.Join(errors.New(f[1]), conn.Close())

File: server.go [hunk 3]
```diff
@@ -180,10 +179,10 @@ func (u *Upgrader) Upgrade(w http.ResponseWriter, r *http.Request, responseHeade
...
 
 	if brw.Reader.Buffered() > 0 {
-		if err := netConn.Close(); err != nil {
-			log.Printf("websocket: failed to close network connection: %v", err)
-		}
-		return nil, errors.New("websocket: client sent data before handshake is complete")
+		return nil, errors.Join(
+			netConn.Close(),
+			errors.New("websocket: client sent data before handshake is complete"),
+		)
```
Comment (GreenMarmot) [inline server.go:185]: Reorder so that primary error is first.

File: server.go [hunk 4]
```diff
@@ -248,32 +247,20 @@ func (u *Upgrader) Upgrade(w http.ResponseWriter, r *http.Request, responseHeade
 
 	// Clear deadlines set by HTTP server.
 	if err := netConn.SetDeadline(time.Time{}); err != nil {
-		if err := netConn.Close(); err != nil {
-			log.Printf("websocket: failed to close network connection: %v", err)
-		}
-		return nil, err
+		return nil, errors.Join(netConn.Close(), err)
```
Comment (GreenMarmot) [inline server.go:250]: Reorder so that primary error is first.

			return nil, errors.Join(err, netConn.Close())

File: server.go [hunk 5]
```diff
@@ -248,32 +247,20 @@ func (u *Upgrader) Upgrade(w http.ResponseWriter, r *http.Request, responseHeade
...
 	}
 
 	if u.HandshakeTimeout > 0 {
 		if err := netConn.SetWriteDeadline(time.Now().Add(u.HandshakeTimeout)); err != nil {
-			if err := netConn.Close(); err != nil {
-				log.Printf("websocket: failed to close network connection: %v", err)
-			}
-			return nil, err
+			return nil, errors.Join(netConn.Close(), err)
```
Comment (GreenMarmot) [inline server.go:255]: Reorder so that primary error is first.

			return nil, errors.Join(err, netConn.Close())

File: server.go [hunk 6]
```diff
@@ -248,32 +247,20 @@ func (u *Upgrader) Upgrade(w http.ResponseWriter, r *http.Request, responseHeade
...
-		return nil, err
+		return nil, errors.Join(netConn.Close(), err)
 	}
 	if u.HandshakeTimeout > 0 {
 		if err := netConn.SetWriteDeadline(time.Time{}); err != nil {
-			if err := netConn.Close(); err != nil {
-				log.Printf("websocket: failed to close network connection: %v", err)
-			}
-			return nil, err
+			return nil, errors.Join(netConn.Close(), err)
```
Comment (GreenMarmot) [inline server.go:263]: Reorder so that primary error is first.

			return nil, errors.Join(err, netConn.Close())

File: server.go [hunk 7]
```diff
@@ -248,32 +247,20 @@ func (u *Upgrader) Upgrade(w http.ResponseWriter, r *http.Request, responseHeade
...
 		}
 	}
 	if _, err = netConn.Write(p); err != nil {
-		if err := netConn.Close(); err != nil {
-			log.Printf("websocket: failed to close network connection: %v", err)
-		}
-		return nil, err
+		return nil, errors.Join(netConn.Close(), err)
```
Comment (GreenMarmot) [inline server.go:259]: Reorder so that primary error is first.

			return nil, errors.Join(err, netConn.Close())

File: proxy.go [hunk 8]
```diff
@@ -58,29 +57,20 @@ func (hpd *httpProxyDialer) Dial(network string, addr string) (net.Conn, error)
 	}
 
 	if err := connectReq.Write(conn); err != nil {
-		if err := conn.Close(); err != nil {
-			log.Printf("httpProxyDialer: failed to close connection: %v", err)
-		}
-		return nil, err
+		return nil, errors.Join(conn.Close(), err)
```
Comment (GreenMarmot) [inline proxy.go:60]: Reorder so that primary error is first.

			return nil, errors.Join(err, conn.Close())

File: client.go [hunk 9]
```diff
@@ -336,9 +332,7 @@ func (d *Dialer) DialContext(ctx context.Context, urlStr string, requestHeader h
 
 	defer func() {
 		if netConn != nil {
-			if err := netConn.Close(); err != nil {
-				log.Printf("websocket: failed to close network connection: %v", err)
-			}
+			err = netConn.Close()
```
Comment (GreenMarmot) [inline client.go:335]: It looks like your intent is to modify the function return value.   That's not what happens here.   [Demonstration](https://go.dev/play/p/5KnGoJG6LqZ).  

If the code is modified so that the return value is set, then primary error is ignored. [Demonstration](https://go.dev/play/p/3UAvH8ga0F4). 

Fix by removing this deferred function call  and changing the error returns below to 

      return nil, nil, errors.Join(err, netConn.Close())

 Delete the the `netConn = nil` statement at the end of the function.

**Review by GreenMarmot — COMMENTED** [review]
With one exception, the logged errors are the result of calling a network connection Close() method on an error path.  It's reasonable to ignore these close errors for two reasons:
- The functions are returning a more important error.
- There's nothing that the application can do with the information in the close error.

I would remove the calls to log.Printf by undoing the changes in 666c197fc9157896b57515c3a3326c3f8c8319fe.   

If you are going to return the close error with errors.Join, then the secondary close error should come last in the list of errors. This does do things:  the primary comes first in the error string; search on the error tree visits the primary error first. 

The one exception is the error returned from `bw.Flush()`.  That call should never return an error.  It is correct to add the call to panic.

File: proxy.go (hunk 1 above)
Comment (apoorvajagtap) [reply proxy.go]: Thanks for catching that @GreenMarmot!

**Comment by GreenMarmot** [comment]
Regarding the deferred function and `netConn = nil` in DialContext:

The original code uses this [defer statement](https://github.com/gorilla/websocket/blob/695e9095ce8736ac99c83939ca6b0fe93768f680/client.go#L337-L343) to cleanup when returning on error:

	defer func() {
		if netConn != nil {
			if err := netConn.Close(); err != nil {
				log.Printf("websocket: failed to close network connection: %v", err)
			}
		}
	}()

The [function assigns nil to netConn](https://github.com/gorilla/websocket/blob/695e9095ce8736ac99c83939ca6b0fe93768f680/client.go#L435-L437) to avoid closing the underlying network connection on successful return:

	netConn = nil // to avoid close in defer.

----

There are two valid ways to remove the call to log.Printf:

The first is to delete the lines of code shown above in this comment and explicitly close the connection on each error return.  Change each of of the return statements after the network connection is dialed to:

    return nil, nil, errors.Join(err, netConn.Close())

This approach fragile because large amount of code between where the network connection is dialed and the success return at the end of the function.  It would be easy to miss adding a call to `netConn.Close()` when editing that code.  However, this approach is consistent with the other changes in the PR.

The second approach is to ignore the error.  As I mentioned in  a previous comment, this is OK because the function is returning a more important error and the close error is not actionable by the application developer.  

	defer func() {
		if netConn != nil {
			_ = netConn.Close()
		}
	}()

I see that the PR now implements the second approach.  If it's agreeable to ignore the error here, then it should be agreeable to ignore the other close errors touched by this PR.

File: client.go [hunk 10]
```diff
@@ -433,7 +427,7 @@ func (d *Dialer) DialContext(ctx context.Context, urlStr string, requestHeader h
 		return nil, nil, err
 	}
 	netConn = nil // to avoid close in defer.
-	return conn, resp, nil
+	return conn, resp, err
```
Comment (GreenMarmot) [inline client.go:430]: It's better to use `return conn, resp, nil` because it makes it clear that this is always a successful return from the function.

**Comment by GreenMarmot** [comment]
This PR changes the error types and values returned from the modified methods. This change might break applications that use the equality operator and type assertions to inspect errors. It's safe to ignore the close errors as I described above. The better fix is to revert the changes in 666c197fc9157896b57515c3a3326c3f8c8319fe.

**Comment by AlexVulaj** [comment]
This looks good to me. @GreenMarmot as you've been extremely helpful with these changes, do you see any further issues with this PR as it is? If not, I'd like to go ahead and merge it.

**Review by AlexVulaj — APPROVED** [review]
